check:
	/usr/local/src/LINARO.Toolchain-2017.10/arm-linux-gnueabihf/abe/testsuite/test.sh
	/usr/local/src/LINARO.Toolchain-2017.10/arm-linux-gnueabihf/abe/test.sh

clean:
	rm -fr builds/* sysroots/*

